// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int belowHalf = 0;
		int aboveHalf = 0;
		for (int counter = 0; counter < N ; counter++) {
			double randomRoll = Math.random();
			if (randomRoll>0.5){
				aboveHalf++;
			}
			else {
				belowHalf++;
			}
		}
		System.out.println("> 0.5 " + aboveHalf + " times");
		System.out.println("<= 0.5 " + belowHalf + " times");

		//ratio calculation:

		if (belowHalf<aboveHalf && belowHalf!= 0 && aboveHalf != 0 ){
			System.out.println("Ratio: " + (double)belowHalf/(double)aboveHalf);
		}
		else if (belowHalf>aboveHalf && belowHalf!= 0 && aboveHalf != 0 ){
			System.out.println("Ratio: " + (double)aboveHalf/(double)belowHalf);
		}
		else {
			System.out.println("Ratio: 1");
		}
	}
}
